/* ============================================================================
 *  LINHA DE VIDA · GD ENGENHARIA
 *  prontuario.js — PRONTUÁRIO / TECHNICAL FILE bilíngue (PT-BR / EN-US)
 *
 *  Dossiê técnico completo e auditável. O idioma, as unidades e o conjunto
 *  normativo seguem o país selecionado (R.pais). Inclui QR Code na plaqueta
 *  (rastreabilidade) e tabela de equivalência normativa internacional.
 * ========================================================================== */
(function (root) {
  'use strict';

  function dep(n) { var x = root.LV && root.LV[n]; if (!x) throw new Error('prontuario.js: ' + n + ' não carregado'); return x; }
  function round(x) { return Math.round(x); }

  function quantitativo(e) {
    var nVaos = +e.nVaos || 1, Lv = +e.L || 0, nUsr = +e.nUsuarios || 1;
    var temAbs = (e.temAbsorvedor === 'Sim' || e.temAbsorvedor === true);
    return {
      materiais: [
        ['poste', nVaos + 1, 'un'], ['placa+chumb', nVaos + 1, 'cj'],
        ['cabo', round(Lv * nVaos * 1.1), 'm'], ['esticador', nVaos, 'un'],
        ['absorvedor', temAbs ? nVaos : 0, 'un'], ['terminacao', 2 * nVaos, 'cj'],
        ['placaguia', Math.max(0, nVaos - 1), 'un'], ['placaid', 1, 'un'], ['epdm', 4 * (nVaos + 1), 'un']
      ],
      epi: [['cinturao', nUsr], ['talabarte', nUsr], ['travaquedas', nUsr], ['capacete', nUsr], ['conector', 2 * nUsr], ['calcado', nUsr]]
    };
  }

  function gerar(R, proj, cfg) {
    var Norms = dep('Norms'), Compat = dep('Compat'), Report = dep('Report'), I18n = dep('I18n'), Draw = root.LV.Draw, QR = root.LV.QR;
    Report.setCtx(R);
    var L = Report.L, U = Report._U, f = Report._f, esc = Report._esc, dataBR = Report._dataBR;
    var e = R.entrada, reg = (proj.registros || {}), pais = R.pais || {};
    var lang = (pais.idioma === 'en') ? 'en' : 'pt';
    // Traduz um VALOR DE DADO exibido (mantém a chave PT para indexação/lookup)
    function dLoc(nome) { return I18n.d(nome, lang); }
    var inox = /Inox/i.test(R.dados.cabo.material);
    var serie = 'GDLV-' + (proj.id || '').slice(-6).toUpperCase() + '-' + new Date().getFullYear();

    function tabela(headers, rows, classe) {
      var s = '<table class="tab ' + (classe || '') + '"><thead><tr>' + headers.map(function (h) { return '<th>' + esc(h) + '</th>'; }).join('') + '</tr></thead><tbody>';
      rows.forEach(function (r) { s += '<tr>' + r.map(function (c, i) { return '<td' + (i === 0 ? '' : ' class="val"') + '>' + (c == null ? '' : esc(c)) + '</td>'; }).join('') + '</tr>'; });
      return s + '</tbody></table>';
    }
    function vazia(headers, n) { var rows = []; for (var i = 0; i < (n || 4); i++) rows.push(headers.map(function () { return ''; })); return tabela(headers, rows, 'preencher'); }
    // Coleta as seções num array (para permitir seleção do que incluir na exportação)
    var SEC = [];
    function secao(id, titulo, conteudo) { SEC.push({ id: id, titulo: titulo, html: '<section class="pr-sec" id="pr-' + id + '"><h2 class="pr-h">' + esc(titulo) + '</h2>' + conteudo + '</section>' }); return ''; }

    var s = '';

    // CAPA
    var capaHtml = '<div class="pr-capa">' + Report.emblema(cfg) + '<div class="cp-emp">' + esc(cfg.empresa) + '</div>' +
      '<div class="cp-sub">' + esc(cfg.responsavel) + ' · ' + esc(cfg.crea) + ' · CNPJ ' + esc(cfg.cnpj) + '</div>' +
      '<div class="cp-titulo">' + L('PRONTUÁRIO DO SISTEMA<br>DE LINHA DE VIDA HORIZONTAL', 'HORIZONTAL LIFELINE<br>SYSTEM TECHNICAL FILE') + '</div>' +
      '<div class="cp-sub2">' + (pais.normas ? pais.normas.join(' · ') : '') + '</div>' +
      '<table class="cp-id"><tbody>' +
      '<tr><td>' + L('Obra / Cliente', 'Project / Client') + '</td><td>' + esc(e.obra || proj.nome) + '</td></tr>' +
      '<tr><td>' + L('Local', 'Site') + '</td><td>' + esc(e.local || '—') + '</td></tr>' +
      '<tr><td>' + L('País / normas', 'Country / standards') + '</td><td>' + (pais.bandeira || '') + ' ' + esc(L(pais.nome || 'Brasil', pais.nomeEn || pais.nome || 'Brazil')) + '</td></tr>' +
      '<tr><td>' + L('Identificação (nº de série)', 'Identification (serial no.)') + '</td><td>' + esc(serie) + '</td></tr>' +
      '<tr><td>' + L('Responsável técnico', 'Engineer of record') + '</td><td>' + esc(e.responsavel || cfg.responsavel) + '</td></tr>' +
      '<tr><td>' + L('Revisão / Emissão', 'Revision / Issued') + '</td><td>' + esc(proj.revisao || 'R00') + ' · ' + dataBR(Date.now()) + '</td></tr>' +
      '<tr><td>' + L('Veredito', 'Verdict') + '</td><td><b class="' + (R.veredito.aprovado ? 'tok' : 'tfail') + '">' + L(R.veredito.aprovado ? 'APROVADO' : 'REPROVADO', R.veredito.aprovado ? 'APPROVED' : 'FAILED') + '</b></td></tr>' +
      '</tbody></table>' + (Draw ? '<div class="fig">' + Draw.iso3D(R) + '</div>' : '') +
      '<div class="cp-rodape">' + L('Documento gerado pelo software Linha de Vida — GD Engenharia. Confidencial.', 'Generated by Lifeline software — GD Engenharia. Confidential.') + '</div></div>';

    // 1 OBJETO
    s += secao('objeto', L('1 · Objeto e dados gerais', '1 · Object and general data'),
      '<p>' + L('Este prontuário consolida o projeto, os memoriais, as especificações, as análises de risco, os planos e os registros do sistema de linha de vida horizontal da obra ',
        'This technical file consolidates the design, reports, specifications, risk analyses, plans and records of the horizontal lifeline system at ') + '<b>' + esc(e.obra || proj.nome) + '</b>.</p>' +
      tabela([L('Parâmetro', 'Parameter'), L('Valor', 'Value')], [
        [L('Cenário / substrato', 'Scenario / substrate'), (e.cenario || '—') + ' / ' + (e.substrato || '—')],
        [L('Ambiente (corrosividade)', 'Environment (corrosivity)'), e.ambiente || '—'],
        [L('Geometria', 'Geometry'), Math.round(R.dados.nVaos.valor) + ' × ' + U(R.dados.L) + ' · ' + L('poste', 'post') + ' ' + U(R.dados.h)],
        [L('Nº de usuários', 'Number of users'), String(Math.round(R.dados.n.valor))],
        [L('Material principal', 'Main material'), inox ? L('Aço inox AISI 316', 'AISI 316 stainless') : L('Aço galvanizado', 'Galvanized steel')]
      ]));

    // 2 NORMAS
    s += secao('normas', L('2 · Normas e premissas adotadas', '2 · Standards and assumptions'),
      '<ul class="prem"><li>' + L('Força no trabalhador', 'Worker force') + ' ≤ ' + f(pais.forcaTrabalhadorMax) + ' kN — ' + esc(pais.refForca || '') + '</li>' +
      '<li>' + L('Ancoragem', 'Anchorage') + ' — ' + esc(pais.refAncoragem || '') + '</li>' +
      '<li>' + L('Linha de vida', 'Lifeline') + ' — ' + esc(pais.refLinha || '') + '</li></ul>');

    // 3 MEMORIAL DESCRITIVO  / 4 MEMORIAL DE CÁLCULO
    s += secao('descritivo', L('3 · Memorial descritivo', '3 · Descriptive report'), Report.memorialDescritivo(R, proj, cfg));
    s += secao('calculo', L('4 · Memorial de cálculo', '4 · Calculation report'), Report.memorialCalculo(R, proj, cfg));

    // 5 MATERIAIS
    s += secao('materiais', L('5 · Especificação técnica de materiais', '5 · Material specification'),
      tabela([L('Componente', 'Component'), 'Inox AISI 316', L('Galvanizado', 'Galvanized'), L('Norma/Obs.', 'Standard/Notes')], [
        [L('Cabo de aço', 'Steel cable'), L('Inox 316, Ø8–12, CR ≥ 5× carga', 'SS 316, Ø8–12, MBL ≥ 5× load'), L('Galv. 6x19+AA', 'Galv. 6x19+IWRC'), L('NBR 16325 / EN 795', 'EN 795 / ANSI Z359')],
        [L('Esticador / tensor', 'Turnbuckle'), L('Inox 316 c/ contraporca', 'SS 316 w/ locknut'), L('Galvanizado', 'Galvanized'), L('Aplica T₀', 'Applies T₀')],
        [L('Absorvedor de linha', 'In-line absorber'), L('Inox calibrado', 'Calibrated SS'), L('Galvanizado', 'Galvanized'), L('NBR 16325 / EN 795', 'EN 795')],
        [L('Poste de ancoragem', 'Anchor post'), L('SHS inox/galv.', 'SHS SS/galv.'), L('SHS A572 galv.', 'SHS A572 galv.'), L('NBR 8800', 'AISC 360')],
        [L('Placa + chumbadores', 'Base plate + anchors'), L('Inox 316', 'SS 316'), L('Galvanizado', 'Galvanized'), esc(pais.refAncoragem || '')]
      ]));

    // 6 COMPATIBILIDADE
    var headC = [L('Substrato', 'Substrate')].concat(Compat.ANCORAGENS.map(function (a) { var rot = dLoc(a); return lang === 'en' ? rot : rot.replace(/ \(.*/, ''); }));
    var rowsC = Object.keys(Compat.MATRIZ).map(function (sub) { return [dLoc(sub)].concat(Compat.MATRIZ[sub]); });
    s += secao('compat', L('6 · Compatibilidade substrato × ancoragem', '6 · Substrate × anchorage compatibility'),
      tabela(headC, rowsC, 'matriz') + '<p class="leg">✔ ' + L('recomendado', 'recommended') + ' · ⚠ ' + L('com restrição', 'restricted') + ' · ✗ ' + L('não permitido', 'not allowed') + ' · – ' + L('não aplicável', 'n/a') + '</p>');

    // 7 QUANTITATIVO
    var q = quantitativo(e);
    var matNome = { poste: L('Poste de ancoragem', 'Anchor post'), 'placa+chumb': L('Placa de base + chumbadores', 'Base plate + anchors'), cabo: L('Cabo de aço', 'Steel cable'), esticador: L('Esticador / tensor', 'Turnbuckle'), absorvedor: L('Absorvedor de linha', 'In-line absorber'), terminacao: L('Terminação + sapatilho', 'Termination + thimble'), placaguia: L('Placa-guia / olhal', 'Guide plate / eye'), placaid: L('Placa de identificação', 'ID plate'), epdm: L('Arruela de vedação EPDM', 'EPDM sealing washer') };
    var epiNome = { cinturao: L('Cinturão paraquedista', 'Full-body harness'), talabarte: L('Talabarte Y c/ absorvedor', 'Y energy-absorbing lanyard'), travaquedas: L('Trava-quedas guiado', 'Guided fall arrester'), capacete: L('Capacete c/ jugular', 'Helmet w/ chin strap'), conector: L('Conector dupla trava', 'Double-locking connector'), calcado: L('Calçado + luvas', 'Boots + gloves') };
    s += secao('quantit', L('7 · Quantitativo de materiais e EPI', '7 · Bill of materials and PPE'),
      '<h3>A · ' + L('Materiais', 'Materials') + '</h3>' + tabela([L('Descrição', 'Description'), L('Qtd.', 'Qty'), L('Un.', 'Unit')], q.materiais.map(function (r) { return [matNome[r[0]], String(r[1]), r[2]]; })) +
      '<h3>B · ' + L('EPI por trabalhador', 'PPE per worker') + '</h3>' + tabela([L('Descrição', 'Description'), L('Qtd.', 'Qty')], q.epi.map(function (r) { return [epiNome[r[0]], String(r[1])]; })));

    // 8 APR
    s += secao('apr', L('8 · Análise Preliminar de Risco (APR)', '8 · Preliminary Risk Analysis (JHA)'),
      tabela([L('Perigo', 'Hazard'), L('Risco', 'Risk'), L('Medidas de controle', 'Controls')], [
        [L('Queda de altura', 'Fall from height'), L('Lesão grave / morte', 'Serious injury / death'), L('100% conectado; trava-quedas; ZLQ verificada', '100% tie-off; fall arrester; clearance verified')],
        [L('Ruptura do cabo', 'Cable failure'), L('Queda', 'Fall'), L('Cabo dimensionado (FS≥2); terminações', 'Cable designed (SF≥2); terminations')],
        [L('Falha da ancoragem', 'Anchorage failure'), L('Colapso', 'Collapse'), L('≥ ' + f(pais.forcaTrabalhadorMax >= 8 ? 22.2 : 15) + ' kN; ensaio de carga', '≥ load test')],
        [L('Suspensão inerte', 'Suspension trauma'), L('Trauma', 'Trauma'), L('Plano de resgate (seção 12)', 'Rescue plan (section 12)')]
      ]));

    // 9 PT
    s += secao('pt', L('9 · Procedimento e Permissão de Trabalho (PT)', '9 · Procedure and Work Permit'),
      '<p>' + L('Procedimento operacional de montagem e utilização; emitir PT antes de cada atividade com base na Análise de Risco.', 'Operating procedure for assembly and use; issue a Work Permit before each task based on the Job Hazard Analysis.') + '</p>' +
      vazia([L('Data', 'Date'), L('Atividade', 'Task'), L('Responsável', 'Responsible'), L('AR nº', 'JHA no.'), L('Liberado por', 'Released by')], 3));

    // 10 INSPEÇÃO
    s += secao('inspecao', L('10 · Plano e registros de inspeção', '10 · Inspection plan and records'),
      '<p>' + L('Inspeção inicial (após instalação), rotineira (antes de cada uso) e periódica (≤ 12 meses). Registrar e descartar elementos danificados.', 'Initial (after install), routine (before each use) and periodic (≤ 12 months) inspection. Record and discard damaged components.') + '</p>' +
      (reg.inspecoes && reg.inspecoes.length ? tabela([L('Data', 'Date'), L('Tipo', 'Type'), L('Inspetor', 'Inspector'), L('Resultado', 'Result'), L('Próxima', 'Next')], reg.inspecoes.map(function (r) { return [dataBR(r.criadoEm), r.tipo, r.inspetor, r.resultado, r.proxima || '']; }))
        : vazia([L('Data', 'Date'), L('Tipo (inicial/rotineira/periódica)', 'Type (initial/routine/periodic)'), L('Inspetor', 'Inspector'), L('Resultado', 'Result'), L('Próxima', 'Next')], 4)));

    // 11 ENSAIO
    s += secao('ensaio', L('11 · Registro de ensaio de carga das ancoragens', '11 · Anchorage load test record'),
      '<p>' + L('Ensaio de comprovação da carga mínima do dispositivo (≥ ', 'Proof load test of the device (≥ ') + U(R.ancoragem.R_anc) + L('), por profissional habilitado.', '), by a qualified person.') + '</p>' +
      (reg.ensaios && reg.ensaios.length ? tabela([L('Data', 'Date'), L('Ponto', 'Point'), L('Exigida', 'Required'), L('Aplicada', 'Applied'), L('Resultado', 'Result')], reg.ensaios.map(function (r) { return [dataBR(r.criadoEm), r.ponto, r.exigida, r.aplicada, r.resultado]; }))
        : vazia([L('Data', 'Date'), L('Ponto de ancoragem', 'Anchor point'), L('Carga exigida', 'Required load'), L('Carga aplicada', 'Applied load'), L('Resultado', 'Result')], 4)));

    // 12 RESGATE
    s += secao('resgate', L('12 · Plano de emergência e resgate', '12 · Emergency and rescue plan'),
      '<p>' + L('Procedimento de resgate em altura para reduzir o tempo de suspensão inerte.', 'High-angle rescue procedure to minimize suspension trauma time.') + '</p>' +
      tabela([L('Item', 'Item'), L('Definição', 'Definition')], [
        [L('Equipe de resgate', 'Rescue team'), '____________________'], [L('Tempo-alvo', 'Target time'), '____ min'],
        [L('Acionamento', 'Emergency call'), L('SAMU 192 / Bombeiros 193', '911 / Fire dept.')]]));

    // 13 CAPACITAÇÃO
    s += secao('capacit', L('13 · Registro de capacitação', '13 · Training records'),
      '<p>' + L('Trabalhadores capacitados (mínimo 8 h) e autorizados; documentação arquivada ≥ 5 anos.', 'Trained (min. 8 h) and authorized workers; records retained ≥ 5 years.') + '</p>' +
      (reg.capacitacao && reg.capacitacao.length ? tabela([L('Trabalhador', 'Worker'), L('Curso', 'Course'), L('Validade', 'Valid until')], reg.capacitacao.map(function (r) { return [r.nome, r.curso, r.validade]; }))
        : vazia([L('Trabalhador', 'Worker'), 'CPF / SSN', L('Curso', 'Course'), L('Carga (h)', 'Hours'), L('Validade', 'Valid until')], 4)));

    // 14 EPI
    s += secao('epi', L('14 · Relação de EPI (certificação e validade)', '14 · PPE list (certification and validity)'),
      vazia(['EPI / PPE', L('Fabricante', 'Manufacturer'), L('Certificação (CA/ANSI)', 'Certification (CA/ANSI)'), L('Validade', 'Validity'), L('Inspeção', 'Inspection')], 5));

    // 15 PLAQUETA + QR
    var qrTxt = serie + '|' + esc((e.obra || proj.nome).slice(0, 24));
    var qrSvg = QR ? QR.svg(qrTxt, { px: 3 }) : '';
    s += secao('placa', L('15 · Plaqueta de identificação do sistema', '15 · System identification plate'),
      '<div class="plaqueta-wrap"><div class="plaqueta"><table class="tab"><tbody>' +
      '<tr><td>' + L('Fabricante / RT', 'Manufacturer / RE') + '</td><td>' + esc(cfg.empresa) + '</td></tr>' +
      '<tr><td>CNPJ</td><td>' + esc(cfg.cnpj) + '</td></tr>' +
      '<tr><td>' + L('Modelo', 'Model') + '</td><td>' + esc(pais.tipoDispositivo || 'tipo C') + ' — ' + esc(R.poste.perfil) + '</td></tr>' +
      '<tr><td>' + L('Nº de série', 'Serial no.') + '</td><td>' + esc(serie) + '</td></tr>' +
      '<tr><td>' + L('Material', 'Material') + '</td><td>' + (inox ? L('Inox AISI 316', 'SS AISI 316') : L('Galvanizado', 'Galvanized')) + '</td></tr>' +
      '<tr><td>' + L('Força máx. aplicável', 'Max. applicable force') + '</td><td>' + U(R.tracao.T) + '</td></tr>' +
      '<tr><td>' + L('Nº máx. de usuários', 'Max. users') + '</td><td>' + Math.round(R.dados.n.valor) + '</td></tr>' +
      '<tr><td>⚠ ' + L('Ler o manual antes do uso', 'Read manual before use') + '</td><td></td></tr>' +
      '</tbody></table></div>' +
      (qrSvg ? '<div class="qr-box"><div class="qr">' + qrSvg + '</div><div class="qr-cap">' + esc(serie) + '<br><span>' + L('escaneie para rastrear', 'scan to track') + '</span></div></div>' : '') +
      '</div>');

    // 16 LIBERAÇÃO
    s += secao('liberacao', L('16 · Termo de entrega técnica e liberação de uso', '16 · Technical handover and release'),
      '<p>' + L('A liberação fica condicionada à correta instalação, à aprovação dos ensaios de carga, à inspeção inicial e à capacitação dos usuários.',
        'Release is conditional upon correct installation, approval of load tests, initial inspection, and user training.') + '</p>' + Report.assinatura(cfg, proj));

    // 17 ART
    s += secao('art', L('17 · Responsabilidade técnica (ART)', '17 · Engineering responsibility'),
      tabela([L('Campo', 'Field'), L('Preenchimento', 'Entry')], [[L('Nº da ART / PE Stamp', 'ART / PE Stamp no.'), '____________'], [L('Responsável técnico', 'Engineer of record'), esc(e.responsavel || cfg.responsavel)], [L('CREA / License', 'CREA / License'), esc(cfg.crea)]]));

    // 18 EQUIVALÊNCIA INTERNACIONAL
    s += secao('equiv', L('18 · Equivalência normativa internacional', '18 · International standards mapping'),
      tabela([L('Tema', 'Topic'), 'Brasil', 'EN (EU)', 'USA'], Norms.EQUIVALENCIAS.map(function (q2) { return [q2.tema, q2.br, q2.en, q2.us]; })));

    // 19 REFERÊNCIAS
    s += secao('refs', L('19 · Referências normativas', '19 · Normative references'),
      '<ul class="refs">' + Norms.listarReferencias().map(function (nx) { return '<li><b>' + esc(nx.codigo) + '</b> — ' + esc(nx.titulo) + '</li>'; }).join('') + '</ul>');

    // Montagem final conforme a seleção (opts.ids) e inclusão da capa (opts.capa)
    var opts = arguments[3] || {};
    var idsSel = opts.ids || null;
    var body = SEC.filter(function (x) { return !idsSel || idsSel.indexOf(x.id) !== -1; }).map(function (x) { return x.html; }).join('');
    var head = (opts.capa === false) ? '' : capaHtml;
    _ultimasSecoes = SEC.map(function (x) { return { id: x.id, titulo: x.titulo }; });
    return '<div class="report prontuario">' + head + body + '</div>';
  }

  // Lista as seções disponíveis {id, titulo} (roda a montagem sem corpo)
  var _ultimasSecoes = [];
  function secoesDisponiveis(R, proj, cfg) {
    gerar(R, proj, cfg, { capa: false, ids: [] });   // popula _ultimasSecoes sem gerar corpo
    return _ultimasSecoes.slice();
  }

  var Prontuario = { gerar: gerar, secoesDisponiveis: secoesDisponiveis, quantitativo: quantitativo };
  root.LV = root.LV || {};
  root.LV.Prontuario = Prontuario;
  if (typeof module !== 'undefined' && module.exports) module.exports = Prontuario;
})(typeof self !== 'undefined' ? self : (typeof globalThis !== 'undefined' ? globalThis : this));
